#!/usr/bin/perl
#
# This is a simple notifier which will submit events to Pushover
#

use strict;
use warnings;

use JSON;
use LWP::UserAgent;


#
# Read the JSON from STDIN
#
my $input = "";
while (my $line = <>) {
      $input .= $line;
  }
print $input;
#
# Decode the JSON to an object
#
my $obj = decode_json( $input );

#
# The subject of the notification pushover receives.
#
my $subject = $obj->{'Subject'};

#
# The body of the alert
#
my $msg = $obj->{'Detail'};

#
# Now send to pushover.
#
my $x = LWP::UserAgent->new();
$x->post( "https://api.pushover.net/1/messages.json",
          [
           "token" => "XX",
           "user" => "YY",
           "message" => $msg,
           title => $subject,
          ]);

#
# All done.
#
exit(0);
